### ISSUE TITLE
looks like a typo

### ISSUE THREAD

**Issue by haochengxia** [lx10077/lx10077.github.io#1]
In https://github.com/lx10077/lx10077.github.io/blob/master/assets/pdf/phd_thesis.pdf , it seems that 'Ststistics' is a typo of 'Statistics'. I am uncertain, but I wanted to report this issue because the cover appears rather peculiar.
![image](https://user-images.githubusercontent.com/44400703/233641545-fbe4580a-a545-45fd-a31e-39ef343310cc.png)

**Comment by lx10077** [comment]
Thanks for your pointing it out. It's indeed a typo. Because recently I need to revise my PhD thesis, I remove the pdf from my website and will upload it again once the revision is finished. Thanks again for improving my thesis :).
